# Generated by Django 4.1 on 2022-08-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='direcciones',
            table='direcciones',
        ),
    ]
