# Generated by Django 4.1 on 2022-08-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'managed': True},
        ),
    ]
